version: "3"
services:
  db:
    restart: always
    image: "postgis/postgis:12-2.5-alpine"
    volumes:
      -  db-data:/var/lib/postgresql/data
    ports: 
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: "db"
      POSTGRES_USER: "db"
      POSTGRES_DB: "db"
      
volumes:
  db-data:
    driver: local